[versions]
assertj = "3.24.2"
assertj-db = "2.0.2"
commons-validator = "1.7"
jqwik = "1.7.3"
junit = "5.10.0-M1"
mockito = "5.2.0"

[libraries]
assertj = { module = "org.assertj:assertj-core", version.ref = "assertj" }
assertj-db = { module = "org.assertj:assertj-db", version.ref = "assertj-db" }
commons-validator = { module = "commons-validator:commons-validator", version.ref = "commons-validator" }
jqwik = { module = "net.jqwik:jqwik", version.ref = "jqwik" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
junit-vintage = { module = "org.junit.vintage:junit-vintage-engine", version.ref = "junit" }
mockito-inline = { module = "org.mockito:mockito-inline", version.ref = "mockito" }
mockito-junit = "org.mockito:mockito-junit-jupiter:5.3.1"

[bundles]
junit = [
    "junit-jupiter",
    "junit-vintage",
]
mockito = [
    "mockito-inline",
    "mockito-junit",
]

[plugins]
version-catalog-update = "nl.littlerobots.version-catalog-update:0.8.0"
versions = "com.github.ben-manes.versions:0.47.0"
